
custom: # Custom properties
  welcome: Welcome to this Spring Project
  

server: # Server Properties
  port: 9090

spring: # Database Connection with Spring Interface
  security: # Security
    user:
      name: Casanova
      password: 123
  
  datasource: # Datasource Details
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/social_media_system
    driver-class-name: org.postgresql.Driver

  jpa: # Hibernate properties
    show-sql: true
    database-platform:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  
  

